### ISSUE TITLE
Connection Warning: Can not create connection with improper name: '/#jtB_gSh1AU_Njcf2AAAC'

### ISSUE THREAD

**Issue by tranphuoctien** [priologic/easyrtc#184]
Node v5.4.0
easyrtc v1.0.15 & v1.0.16 beta

roomCreate fired! Trying to create: default
warning - EasyRTC: Can not create connection with improper name: '/#R5YGrskH2YTJ97suAAAA'
error   - EasyRTC: [/#R5YGrskH2YTJ97suAAAA] General authentication error. Socket disconnected.
Stack Trace:
------------
Connection Warning: Can not create connection with improper name: '/#R5YGrskH2YTJ97suAAAA'
    at Object.appObj.createConnection (/home/API_CHAT/apichat/node_modules/easyrtc/lib/easyrtc_public_obj.js:2466:22)
    at async.waterfall.connectionObj (/home/API_CHAT/apichat/node_modules/easyrtc/lib/easyrtc_default_event_listeners.js:271:20)
    at fn (/home/API_CHAT/apichat/node_modules/async/lib/async.js:582:34)
    at Immediate._onImmediate (/home/API_CHAT/apichat/node_modules/async/lib/async.js:498:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

What's wrong?

**Comment by tranphuoctien** [comment]
Yeah,We can fix it, Change version socket.io, because easyrtc dont support socket.io v1.4.x. We just install socket.io v1.0.x.
It's Work fine! :)
Thank Easyrtc!

**Comment by ShiYw** [comment]
I've ran into this error too.
But, npm keeping "amitter...network" while I removed the new version and trying to install the former version .
I've tried @1.0  @1.0.1 @1.0.* @1.0.x
all the same.

my trace back:
>warning - EasyRTC: Can not create connection with improper name: '/#E2GvdFSNNZM_IUQ2AAAJ'
error   - EasyRTC: [/#E2GvdFSNNZM_IUQ2AAAJ] General authentication error. Socket disconnected. 
Stack Trace:
------------
Connection Warning: Can not create connection with improper name: '/#E2GvdFSNNZM_IUQ2AAAJ'
    at Object.appObj.createConnection (/home/xiaodan/node.js/node_modules/easyrtc/lib/easyrtc_public_obj.js:2466:22)
    at async.waterfall.connectionObj (/home/xiaodan/node.js/node_modules/easyrtc/lib/easyrtc_default_event_listeners.js:271:20)
    at fn (/home/xiaodan/node.js/node_modules/async/lib/async.js:582:34)
    at Object._onImmediate (/home/xiaodan/node.js/node_modules/async/lib/async.js:498:34)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
------------

**Comment by ShiYw** [comment]
it seems that it is 0.9.16 since it is pointted out in the package.josn

**Comment by ShiYw** [comment]
it works

**Comment by hthetiot** [comment]
Still we need to upgrade socket.io to 1.4.5 ASAP.
@dryswabbie @EricDavies

**Comment by alangibson** [comment]
+1 for upgrading to a more recent version of socket.io. I just had a situation where I was getting warnings

warn - unknown transport: "undefined"

when I tried to connect with socket.io-client 1.4.8.

Workaround is 
1. Change socket.io version to 1.4.x in package.json
2. npm update
3. In easyrtc_default_options.js, replace
option.easyrtcidRegExp = /^[a-z0-9_.-]{1,32}$/i; // EasyRTC socket id (easyrtcid)
with
option.easyrtcidRegExp = /^\/{1}#{1}[a-z0-9_.-]{1,32}$/i;

(credit: https://easyrtc.com/forums/viewthread/169/#170)

**Comment by pdxbenjamin** [comment]
@alangibson 

When I try your work around, i get an error.  The first { on the regex?


`/var/www/html/domain/node/easyrtc/lib/easyrtc_default_options.js:68
option.easyrtcidRegExp 	    = /^/{1}#{1}[a-z0-9_.-]{1,32}$/i;
                       	         ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/html/domain/node/easyrtc/lib/easyrtc_private_obj.js:10:23)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)`
