### ISSUE TITLE
Error: Cannot find module 'express' 

### ISSUE THREAD

**Issue by kscorpio** [priologic/easyrtc#206]
after npm install

pi@raspberrypi ~/easyrtc-master $ node server_example/server.js 
 module.js:341     throw err;   
  ^  Error: Cannot find module 'express'    
at Function.Module._resolveFilename (module.js:339:15)     
at Function.Module._load (module.js:290:25)     
at Module.require (module.js:367:17)    
 at require (internal/module.js:16:19)     
at Object.<anonymous> (/home/pi/easyrtc-master/server_example/server.js:3:15)     
at Module._compile (module.js:413:34)    
 at Object.Module._extensions..js (module.js:422:10)     
at Module.load (module.js:357:32)     
at Function.Module._load (module.js:314:12)    
 at Function.Module.runMain (module.js:447:10)

**Comment by hthetiot** [comment]
@kscorpio You need to perform "npm install" into "server_example" directory.
Doing "npm install" into root directory will only install easyrtc lib dependency, not the server sample ones.
