### ISSUE TITLE
issue installing onwindows 

### ISSUE THREAD

**Issue by alimhabib** [priologic/easyrtc#309]
I followed the steps on the site to install on windows server : 

d:\EasyRTC>node server.js
module.js:471
    throw err;
    ^

Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (d:\EasyRTC\server.js:6:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Any idea please

**Comment by EricDavies** [comment]
d:\EasyRTC> cd server_example
d:\EasyRTC\server_example> node server.js

which file were those steps in? so I know what to fix.

**Comment by alimhabib** [comment]
I got the server_example contents to D:\EasyRTC so  server.js on the top of this directory

**Comment by EricDavies** [comment]
The server.js file contains a line that reads:
   var easyrtc = require("../"); 
which is to say, it is a relative path.
If you've moved things to the structure of:
     d:\EasyRTC\  
             files from server_example directory

    d:\EasyRTC\easyrtc
             contents of easyrtc distribution

Then you'd need to change that line to
   var easyrtc = require("./easyrtc/");

Make sure you do an npm install in both directories of course.
