### ISSUE TITLE
Overriding msgTypeRoomJoin causes server crash

### ISSUE THREAD

**Issue by archasek** [priologic/easyrtc#319]
When I override this event listener, I get an easyrtc server crash.

`easyrtc.events.on('msgTypeRoomJoin', function (connectionObj, rooms, socketCallback, next) {});`

```
 2017-06-09T12:30:41.031Z - warning - EasyRTC: Attempt to request non-existent room name: 'xxxxxxxxxxxxxx' undefined
 Application Warning: Attempt to request non-existent room name: 'xxxxxxxxxxxxxx'
     at Object.appObj.room (C:\workspace\abeedesk\app\easyrtc\lib\easyrtc_public_obj.js:2898:22)
     at EventEmitter.<anonymous> (C:\workspace\abeedesk\app\app.js:126:12)
     at emitMany (events.js:127:13)
     at EventEmitter.emit (events.js:201:7)
     at C:\workspace\abeedesk\app\easyrtc\lib\easyrtc_default_event_listeners.js:569:32
     at fn (C:\workspace\abeedesk\app\easyrtc\node_modules\async\lib\async.js:582:34)
     at Immediate._onImmediate (C:\workspace\abeedesk\app\easyrtc\node_modules\async\lib\async.js:498:34)
     at tryOnImmediate (timers.js:543:15)
     at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by EricDavies** [comment]
I'm not the server guy, but my immediate thought is: I would need to know what your overriding code looks like.  When you override one of the server event methods, your code has to either call the original code itself, or supply similar functionality.

**Comment by archasek** [comment]
My fixed custom `msgTypeRoomJoin` event listener doesn't crash the server now, but I'm still getting warnings even when there is a `roomAutoCreateEnable` server option set to true and I manually call `createRoom()`. Please see the code below.

```
var maxRoomPeers = 4;

easyrtc.events.on('msgTypeRoomJoin', function (connectionObj, rooms, socketCallback, next) {
    var appObj = connectionObj.getApp();
    var roomName = rooms[Object.keys(rooms)[0]].roomName;

    appObj.room(roomName, function (err, roomObj) {
        if (roomObj) {
            roomObj.getConnectionCount(function (err, count) {
                if (count >= maxRoomPeers) {
                    console.log(`${getUserId(connectionObj)} Max room peers number exceeded, rejecting to join #${roomName}`)
                } else {
                    easyrtc.events.defaultListeners.msgTypeRoomJoin(connectionObj, rooms, socketCallback, next);
                }
            });
        } else {
            appObj.createRoom(roomName, null, function (err, roomObj) {
                console.log('Created room #' + roomObj.getRoomName());

                easyrtc.events.defaultListeners.msgTypeRoomJoin(connectionObj, rooms, socketCallback, next);
            });
        }
    });
});
```
