### ISSUE TITLE
Master branch broken throw new errors.Error('ERR_SERVER_ALREADY_LISTEN'); on MacOS

### ISSUE THREAD

**Issue by FelipeMiranda** [priologic/easyrtc#371]
```
npm -v
5.6.0
```

```
node -v
v9.5.0
```

`Darwin localhost.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
`

```
$ node server.js
info    - EasyRTC: Starting EasyRTC Server (v1.1.0) on Node (v9.5.0)
debug   - EasyRTC: Emitting event 'startup'
debug   - EasyRTC: Running func 'onStartup'
net.js:1446
    throw new errors.Error('ERR_SERVER_ALREADY_LISTEN');
    ^

Error [ERR_SERVER_ALREADY_LISTEN]: Listen method has been called more than once without closing.
    at Server.listen (net.js:1446:11)
    at Object.<anonymous> (/Users/felipe/Projects/vivigo/nativeRTC/easyrtc/server_example/server.js:57:11)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
info    - EasyRTC: Starting EasyRTC Server (v1.1.0) on Node (v9.5.0)
debug   - EasyRTC: Emitting event 'startup'
debug   - EasyRTC: Running func 'onStartup'
net.js:1446
    throw new errors.Error('ERR_SERVER_ALREADY_LISTEN');
    ^

Error [ERR_SERVER_ALREADY_LISTEN]: Listen method has been called more than once without closing.
    at Server.listen (net.js:1446:11)
    at Object.<anonymous> (/Users/felipe/Projects/vivigo/nativeRTC/easyrtc/server_example/server.js:57:11)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3

```
**## Steps to reproduce:**

`$ git clone https://github.com/priologic/easyrtc.git`
`$ cd easyrtc`
`$ npm install`
`$ cd server_example`
`$ npm install`
`$ node server.js`

**Comment by gatno** [comment]
Same issue here with windows

**Comment by hthetiot** [comment]
thx @gatno @FelipeMiranda I fixed on master and beta.
