### ISSUE TITLE
buildPeerConnection error: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by AMontagu** [priologic/easyrtc#398]
Hello !

I meet a problem when I perform a call after a f5 reloading page during a call. The easyrtcErrorDialog appear and show SYSTEM_ERR title. With the stacktrace on the console it appear to be a buildPeerConnection error.

I think that maybe a disconnect state is not going well or I need to implement it myself just don't know where to look. I try hangupAll and disconnect onbeforeunload callback without success.

There is the stack trace:
```
debug 2018-06-07T08:30:13.565Z : received message of type roomData [    at n.emit (http://localhost:8080/socket.io/socket.io.js:2:28725)]
easyrtc.js:3595 debug 2018-06-07T08:30:13.581Z : received message of type roomData [    at n.emit (http://localhost:8080/socket.io/socket.io.js:2:28725)]
easyrtc.js:3595 debug 2018-06-07T08:30:14.009Z : received message of type offer [    at n.emit (http://localhost:8080/socket.io/socket.io.js:2:28725)]
easyrtc.js:3595 debug 2018-06-07T08:30:14.010Z : offer accept=true [    at Easyrtc.acceptCheck (http://localhost:8080/easyrtc/easyrtc.js:3753:9)]
easyrtc.js:3595 debug 2018-06-07T08:30:14.012Z : building peer connection to VUOvDdiD4zsAbWXT [    at doAnswerBody (http://localhost:8080/easyrtc/easyrtc.js:6696:18)]
easyrtc.js:3595 debug 2018-06-07T08:30:14.137Z : buildPeerConnection error [    at doAnswerBody (http://localhost:8080/easyrtc/easyrtc.js:6696:18)]
easyrtc.js:3598 debug 2018-06-07T08:30:14.137Z :  RangeError: Maximum call stack size exceeded
    at iceServer (blob:http://localhost:3003/0c8ec5d6-640a-42ef-9cda-b95e1c98e82e:199)
    at safeCopyArray (blob:http://localhost:3003/0c8ec5d6-640a-42ef-9cda-b95e1c98e82e:178)
    at protectConfiguration (blob:http://localhost:3003/0c8ec5d6-640a-42ef-9cda-b95e1c98e82e:197)
    at new WrappedRTCPeerConnection (blob:http://localhost:3003/0c8ec5d6-640a-42ef-9cda-b95e1c98e82e:291)
    at new window.RTCPeerConnection (easyrtc.js:758)
    at new WrappedRTCPeerConnection (blob:http://localhost:3003/0c8ec5d6-640a-42ef-9cda-b95e1c98e82e:300)
    at new window.RTCPeerConnection (easyrtc.js:758)
    at new WrappedRTCPeerConnection (blob:http://localhost:3003/0c8ec5d6-640a-42ef-9cda-b95e1c98e82e:300)
    at new window.RTCPeerConnection (easyrtc.js:758)
    at new WrappedRTCPeerConnection (blob:http://localhost:3003/0c8ec5d6-640a-42ef-9cda-b95e1c98e82e:300)
easyrtc.js:3595 debug 2018-06-07T08:30:14.140Z : saw error SYSTEM_ERR [    at Easyrtc.showError (http://localhost:8080/easyrtc/easyrtc.js:4188:14)]
easyrtc.js:3595 debug 2018-06-07T08:30:14.140Z : buildPeerConnection failed. Call not answered [    at doAnswer (http://localhost:8080/easyrtc/easyrtc.js:6800:13)]
```

I successfully reproduced this bug in demo_audio_video_simple that print me in the console:

```
easyrtc.js:6813 Uncaught buildPeerConnection failed, call not completed
callBody @ easyrtc.js:6813
Easyrtc.call @ easyrtc.js:6951
performCall @ demo_audio_video_simple.js:42
(anonymous) @ demo_audio_video_simple.js:26
```

**Comment by hthetiot** [comment]
@AMontagu did you use the beta branch ?
Can you try the beta branch and let me know.

Finally, can you try if you can reproduce with the last beta docker here:
- https://easyrtc.sylaps.net/demos/demo_audio_video_simple.html

If that confirmed I will fix it.

**Comment by AMontagu** [comment]
hello @hthetiot 

Indeed I can't reproduce this bug with the new beta branch ! 

Great job ;)
