### ISSUE TITLE
Add additional checks to determine if connection has disconnected

### ISSUE THREAD

**Issue by dryswabbie** [priologic/easyrtc#63]
connectionObj functions should each include an additional check to ensure the connection has not disconnected in the middle of handling a request.

Related to issue reported in the EasyRTC support forum:

    TypeError: Cannot read property 'field' of undefined
        at Object.connectionObj.getFields (/var/www/clients/client2/web9/web/ttchat/node_modules/easyrtc/lib/easyrtc_public_obj.js:1516:71)
        at async.waterfall.tokenMsg.msgData.field (/var/www/clients/client2/web9/web/ttchat/node_modules/easyrtc/lib/easyrtc_default_event_listeners.js:1000:27)
        at fn (/var/www/clients/client2/web9/web/ttchat/node_modules/easyrtc/node_modules/async/lib/async.js:582:34)
        at Object._onImmediate (/var/www/clients/client2/web9/web/ttchat/node_modules/easyrtc/node_modules/async/lib/async.js:498:34)
        at processImmediate [as _immediateCallback] (timers.js:317:15)

See  https://groups.google.com/forum/#!topic/easyrtc/xGRo3mDzQBo

**Comment by hthetiot** [comment]
See push request #261
